# Generated by Django 3.1 on 2020-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.TextField(default='NA')),
                ('place_db', models.TextField(default='NA')),
                ('month_db', models.TextField(default='NA')),
                ('year_db', models.TextField(default='NA')),
                ('startingPrice_db', models.TextField(default='NA')),
                ('maximumPrice_db', models.TextField(default='NA')),
                ('customerName_db', models.TextField(default='NA')),
            ],
        ),
    ]
